<Project>

  <Import Project="../Directory.Build.targets"/>

  <ItemGroup>
    <ProjectReference Include="$(SolutionDir)/ChartTools.Common/ChartTools.Common.csproj" Properties="TargetFramework=$(TestTargetFramework)"/>
    <ProjectReference Include="$(SolutionDir)/ChartTools/ChartTools.csproj" Properties="TargetFramework=$(TestTargetFramework)"/>
  </ItemGroup>

</Project>
