using static ChartTools.Generator.Metadata.MetadataHelper;

using ChartTools.Meta;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics;
using System.Linq;
using System.Text;

namespace ChartTools.Generator.Metadata;

[Generator]
public class MetadataMergeGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		if (!Debugger.IsAttached)
		{
			// Uncomment this line to be prompted to debug on generation
			//Debugger.Launch();
		}

		IncrementalValueProvider<ImmutableArray<MetadataGroupProperty>> groups =
			context.SyntaxProvider.ForAttributeWithMetadataName(
				$"{AttributeNamespace}.{nameof(MetadataGroupAttribute)}",
				predicate: static (node, _) => node is PropertyDeclarationSyntax,
				transform: static (context, _) => new MetadataGroupProperty(
					Name: context.TargetSymbol.Name,
					Type: (context.TargetSymbol as IPropertySymbol)!.Type.Name,
					ContainingType: context.TargetSymbol.ContainingType.Name))
			.Collect();

		IncrementalValueProvider<ImmutableArray<MetadataProperty>> properties =
			context.SyntaxProvider.CreateSyntaxProvider(
				predicate: static (node, _) => node is ClassDeclarationSyntax cds && cds.Identifier.Text == MetadataType,
				transform: static (context, _) =>
					from pds in context.Node.DescendantNodes().OfType<PropertyDeclarationSyntax>()
					let symbol = context.SemanticModel.GetDeclaredSymbol(pds) as IPropertySymbol
					where symbol is not null && !symbol.IsReadOnly && !symbol.IsWriteOnly
					select new MetadataProperty(
						Name: symbol.Name,
						Type: symbol.Type.Name,
						ContainingType: symbol.ContainingType.Name))
			.SelectMany(static (p, _) => p)
			.Collect();

		context.RegisterSourceOutput(properties.Combine(groups),
			static (ctx, tuple) => GenerateMergeMethod(ctx, tuple.Left, tuple.Right));
	}

	private static void GenerateMergeMethod(SourceProductionContext context, ImmutableArray<MetadataProperty> properties, ImmutableArray<MetadataGroupProperty> groups)
	{
		StringBuilder builder = new(
$$"""
// <auto-generated/>
using System.Collections.Generic;
using System.Linq;

namespace ChartTools.Meta;

public sealed partial class Metadata
{
	public partial void Merge(params IEnumerable<Metadata> metadata)
	{
		foreach (Metadata mergeItem in metadata)
		{

""");

		Dictionary<string, string> paths = GetGroupPaths(in groups);

		MetadataProperty[] validProperties = [.. properties.Where(p => paths.ContainsKey(p.ContainingType))];

		foreach (string pathKey in paths.Keys)
		{
			string prefix = paths[pathKey];

			if (prefix.Length > 0)
				prefix = prefix + '.';

			IEnumerable<MetadataProperty>
				propsForType = validProperties.Where(p => p.ContainingType == pathKey),
				primitiveProps = propsForType.Where(p => !groups.Any(g => g.Type == p.Type));

			foreach (MetadataProperty prop in primitiveProps)
			{
				string propPath = prefix + prop.Name;

				builder.AppendLine($"""
				if (mergeItem.{propPath} is not null)
					this.{propPath} = mergeItem.{propPath};
""");
			}
		}

		builder.AppendLine("""
		}
	}
}
""");

		context.AddSource("Metadata_Merge.g.cs", builder.ToString());
	}
}
