namespace ChartTools.IO.Sources;

/// <summary>
/// Represents data sources that can be used as a <see cref="System.IO.Stream"/>. This is an abstract class.
/// </summary>
/// <param name="stream">Stream to source from. Derived types can impose minimum read/write access.</param>
public abstract class DataSource(Stream stream) : IDisposable
{
	/// <summary>
	/// Source file path if one was used to create the source
	/// </summary>
	public string? Path { get; }

	/// <summary>
	/// Usable stream provided or generated
	/// </summary>
	/// <remarks>Read/write access defined by the source's runtime type</remarks>
	public Stream Stream { get; } = stream;

	/// <summary>
	/// The stream should be disposed along with the source.
	/// </summary>
	private readonly bool _disposeStream = false;

	/// <summary>
	/// Base constructor to create a <see cref="DataSource"/> from a file path
	/// </summary>
	/// <param name="path">File path</param>
	/// <param name="mode">How the file should be opened</param>
	/// <param name="access">Read/write access</param>
	/// <param name="share">External permissions while the file is open</param>
	/// <remarks>Initializes the stream as a <see cref="FileStream"/> that is disposed with the source.</remarks>
	public DataSource(string path, FileMode mode, FileAccess access, FileShare share) : this(new FileStream(path, mode, access, share))
	{
		Path = path;
		_disposeStream = true;
	}

	/// <summary>
	/// Disposes the source with the stream if generated by the source.
	/// </summary>
	public virtual void Dispose()
	{
		if (_disposeStream)
			Stream.Dispose();

		GC.SuppressFinalize(this);
	}
}
