using ChartTools.Meta;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics;
using System.Linq;
using System.Text;

namespace ChartTools.Generator;

/// <summary>
/// Generates mapping methods between <see cref="Metadata"/> properties and their corresponding keys in different file formats, as defined by <see cref="MetadataKeyAttribute"/>
/// </summary>
[Generator]
public class MetadataMapGenerator : IIncrementalGenerator
{
	private const string
		MetadataType       = "Metadata",
		MapperNamespace    = $"{nameof(ChartTools)}.{nameof(Meta)}.Mapping",
		AttributeNamespace = $"{nameof(ChartTools)}.{nameof(Meta)}";

	private record class MetadataProperty(string Name, string Type, string ContainingType);

	private record class MetadataKeyBind(MetadataProperty Property, MetadataKeyAttribute Attribute);

	private record class MetadataGroupProperty(string Name, string Type, string ContainingType);

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		if (!Debugger.IsAttached)
		{
			// Uncomment this line to be prompted to debug on generation
			//Debugger.Launch();
		}

		IncrementalValueProvider<ImmutableArray<MetadataGroupProperty>> groups =
			context.SyntaxProvider.ForAttributeWithMetadataName(
				$"{AttributeNamespace}.{nameof(MetadataGroupAttribute)}",
				predicate: static (node, _) => node is PropertyDeclarationSyntax,
				transform: static (context, _) => new MetadataGroupProperty(
				Name: context.TargetSymbol.Name,
				Type: (context.TargetSymbol as IPropertySymbol)!.Type.Name,
				ContainingType: context.TargetSymbol.ContainingType.Name))
			.Collect();

		IncrementalValuesProvider<MetadataKeyBind> provider =
			context.SyntaxProvider.ForAttributeWithMetadataName($"{AttributeNamespace}.{nameof(MetadataKeyAttribute)}",
				predicate: static (node, _) => node is PropertyDeclarationSyntax,
				transform: static (context, _) =>
				{
					IPropertySymbol target = (IPropertySymbol)context.TargetSymbol;

					MetadataProperty property = new(
						Name: target.Name,
						Type: target.Type.TypeKind == TypeKind.Class
						? target.Type.Name
						// Extract the underlying type from Nullable<T>
						: (target.Type as INamedTypeSymbol)!.TypeArguments[0].Name,
						ContainingType: target.ContainingType.Name);

					return context.Attributes.Select(
						attribute =>
						{
							KeyValuePair<string, TypedConstant> mappable =
								attribute.NamedArguments
									.FirstOrDefault(static arg => arg.Key == nameof(MetadataKeyAttribute.ValueMappable));

							FileType attFileType = (FileType)attribute.ConstructorArguments[0].Value!;
							string attKey = (string)attribute.ConstructorArguments[1].Value!;

							return new MetadataKeyBind(property, mappable.Key is null
								? new(attFileType, attKey)
								: new(attFileType, attKey) { ValueMappable = (bool)mappable.Value.Value! });
						}).ToImmutableArray();
				}).SelectMany(static (binds, _) => binds);

		RegisterMapper("MetadataChartMapper", FileType.Chart);
		RegisterMapper("MetadataIniMapper", FileType.Ini);

		void RegisterMapper(string mapperType, FileType fileType)
		{
			IncrementalValuesProvider<MetadataKeyBind> fileTypeProvider = provider
				.Where(bind => bind.Attribute.FileType == fileType);

			context.RegisterImplementationSourceOutput(
			   fileTypeProvider
				   .Where(static bind => bind.Attribute.ValueMappable).Collect()
			   .Combine(groups),
			   (ctx, tuple) => GenerateMapMethods(mapperType, in ctx, tuple));

			context.RegisterImplementationSourceOutput(fileTypeProvider.Collect().Combine(groups),
				(ctx, tuple) => GenerateNonMapMethods(mapperType, in ctx, tuple));
		}
	}

	private static Dictionary<string, string> GetGroupPaths(in ImmutableArray<MetadataGroupProperty> groups)
	{
		Dictionary<string, string> paths = new(groups.Length);

		do
			foreach (MetadataGroupProperty group in groups)
			{
				if (paths.ContainsKey(group.Type))
					continue;

				if (group.ContainingType is MetadataType)
					paths[group.Type] = $".{group.Name}";
				else if (paths.TryGetValue(group.ContainingType, out var path))
					paths[group.Type] = $"{path}.{group.Name}";
			}
		while (paths.Count < groups.Length);

		// Shorthand to not have to check for root
		paths[MetadataType] = string.Empty;

		return paths;
	}

	private static void GenerateMapMethods
		(string className, in SourceProductionContext context,
		(ImmutableArray<MetadataKeyBind>, ImmutableArray<MetadataGroupProperty>) tuple)
	{
		var (binds, groups) = tuple;

		Dictionary<string, string> paths = GetGroupPaths(in groups);

		StringBuilder builder = new(
$$"""
// <auto-generated/>

using ChartTools.IO;

namespace {{MapperNamespace}};

internal sealed partial class {{className}}
{

""");

		if (context.CancellationToken.IsCancellationRequested)
			return;

		BuildTryGet(builder, in binds, paths);

		if (context.CancellationToken.IsCancellationRequested)
			return;

		BuildTrySet(builder, in binds, paths);

		builder.AppendLine(
"""
}
""");

		if (context.CancellationToken.IsCancellationRequested)
			return;

		context.AddSource($"{className}_Map.g.cs", builder.ToString());
	}

	private static void GenerateNonMapMethods
	(string className, in SourceProductionContext context,
	(ImmutableArray<MetadataKeyBind>, ImmutableArray<MetadataGroupProperty>) tuple)
	{
		var (binds, groups) = tuple;

		Dictionary<string, string> paths = GetGroupPaths(in groups);

		StringBuilder builder = new(
$$"""
// <auto-generated/>

using ChartTools.IO;

namespace {{MapperNamespace}};

internal sealed partial class {{className}}
{

""");

		if (context.CancellationToken.IsCancellationRequested)
			return;

		BuildTryRemove(builder, in binds, paths);

		if (context.CancellationToken.IsCancellationRequested)
			return;

		BuildTryContains(builder, in binds, paths);

		if (context.CancellationToken.IsCancellationRequested)
			return;

		BuildGetAll(builder, in binds, paths);

		builder.AppendLine(
"""
}
""");

		if (context.CancellationToken.IsCancellationRequested)
			return;

		context.AddSource($"{className}_Misc.g.cs", builder.ToString());
	}

	private static void BuildTryGet(StringBuilder builder, in ImmutableArray<MetadataKeyBind> binds, Dictionary<string, string> paths)
	{
		builder.AppendLine(
$$"""
	private static partial bool TryGetFromAttribute({{MetadataType}} metadata, in ReadOnlySpan<char> key, out string value)
		=> (value = key switch
		{
""");

		foreach (MetadataKeyBind bind in binds)
		{
			string toStringSuffix = bind.Property.Type is "String"
				? string.Empty : "?.ToString()";

			builder.AppendLine(
$"""
			"{bind.Attribute.Key}" => metadata{paths![bind.Property.ContainingType]}.{bind.Property.Name}{toStringSuffix},
""");
		}

		builder.AppendLine(
"""
			_ => null
		}) is not null;
""");
	}

	private static void BuildTrySet(StringBuilder builder, in ImmutableArray<MetadataKeyBind> binds, Dictionary<string, string> paths)
	{
		builder.AppendLine(
$$"""
	private static partial bool TrySetFromAttribute({{MetadataType}} metadata, in ReadOnlySpan<char> key, in ReadOnlySpan<char> value)
	{
		switch (key)
		{
""");

		foreach (MetadataKeyBind bind in binds)
		{
			string setCode = bind.Property.Type == "String"
				? "value.ToString()"
				: $"ValueParser.Parse<{bind.Property.Type}>(in value, \"{bind.Property.Name}\")";

			builder.AppendLine(
$"""
			case "{bind.Attribute.Key}":
				metadata{paths![bind.Property.ContainingType]}.{bind.Property.Name} = {setCode};
				return true;
""");
		}

		builder.AppendLine(
"""
			default:
				return false;
		}
	}
""");
	}

	private static void BuildTryRemove(StringBuilder builder, in ImmutableArray<MetadataKeyBind> binds, Dictionary<string, string> paths)
	{
		builder.AppendLine(
$$"""
	private static partial bool TryRemoveFromAttribute({{MetadataType}} metadata, in ReadOnlySpan<char> key)
	{
		switch (key)
		{
""");

		foreach (MetadataKeyBind bind in binds)
		{
			builder.AppendLine(
$"""
			case "{bind.Attribute.Key}":
				metadata{paths![bind.Property.ContainingType]}.{bind.Property.Name} = null;
				return true;
""");
		}

		builder.AppendLine(
"""
			default:
				return false;
		}
	}
""");
	}

	private static void BuildTryContains(StringBuilder builder, in ImmutableArray<MetadataKeyBind> binds, Dictionary<string, string> paths)
	{
		builder.AppendLine(
$$"""
	private static partial bool? TryContainsFromAttribute({{MetadataType}} metadata, in ReadOnlySpan<char> key)
		=> key switch
		{
""");

		foreach (MetadataKeyBind bind in binds)
		{
			builder.AppendLine(
$"""
			"{bind.Attribute.Key}" => metadata{paths![bind.Property.ContainingType]}.{bind.Property.Name} is not null,
""");
		}

		builder.AppendLine(
"""
			_ => null
		};
""");
	}

	private static void BuildGetAll(StringBuilder builder, in ImmutableArray<MetadataKeyBind> binds, Dictionary<string, string> paths)
	{
		builder.AppendLine(
$$"""
	private partial IEnumerable<TextEntry> GetAllFromAttributes({{MetadataType}} metadata)
	{
		string value;
""");

		if (binds.Length == 0)
		{
			builder.AppendLine(
"""
		return Eumerable.Empty<TextEntry>();
""");

			return;
		}

		foreach (MetadataKeyBind bind in binds)
		{
			builder.AppendLine(
$"""
		if ((value = Get(metadata, "{bind.Attribute.Key}")) is not null)
			yield return new("{bind.Attribute.Key}", value);
""");
		}

		builder.AppendLine(
"""
	}
""");
	}
}
