<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RunPostBuildEvent>Always</RunPostBuildEvent>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="api\**"/>
    <Compile Remove="_site\**"/>
    <EmbeddedResource Remove="api\**"/>
    <EmbeddedResource Remove="_site\**"/>
    <None Remove="api\**"/>
    <None Remove="_site\**"/>
    <None Remove="log.txt"/>
    <Using Remove="Polyfills"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Docfx.App" Version="2.78.5"/>
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="5.0.0"/>
  </ItemGroup>

</Project>
