<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(MultiTargetFrameworks)</TargetFrameworks>
    <RootNamespace>ChartTools</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Polyfill" Version="9.23.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <InternalsVisibleTo Include="ChartTools;ChartTools.Generator;$(TestAssemblies)"/>
  </ItemGroup>

  <PropertyGroup>
    <PolyArgumentExceptions>true</PolyArgumentExceptions>
  </PropertyGroup>

</Project>
