<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(MultiTargetFrameworks)</TargetFrameworks>
    <RootNamespace>ChartTools</RootNamespace>
	  <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ChartTools;ChartTools.Generator;$(TestAssemblies)"/>
  </ItemGroup>

</Project>
