<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1;net10.0</TargetFrameworks>
    <RootNamespace>ChartTools</RootNamespace>
    <LangVersion>14.0</LangVersion>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="IndexRange" Version="1.1.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Undefined.IsExternalInit" Version="2.0.0" />
  </ItemGroup>

</Project>
