<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;netstandard2.1;net8.0;net9.0;net10.0</TargetFrameworks>
		<LangVersion>14.0</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<SignAssembly>False</SignAssembly>
		<Description>Library for editing Clone Hero song files in .NET</Description>
		<PackageProjectUrl></PackageProjectUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
		<RepositoryUrl>https://github.com/TheBoxyBear/charttools</RepositoryUrl>
		<NeutralLanguage>en-CA</NeutralLanguage>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<Company>TheBoxyBear</Company>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<RunPostBuildEvent>OnOutputUpdated</RunPostBuildEvent>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\LICENSE">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ChartTools.Common\ChartTools.Common.csproj" />
		<ProjectReference Include="..\ChartTools.Generator\ChartTools.Generator.csproj" OutputItemType="Analyzer" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0' Or '$(TargetFramework)' == 'netstandard2.1'">
		<Reference Include="Bcl.CollectionsMarshal">
			<HintPath>..\Dependencies\bin\$(TargetFramework)\Bcl.CollectionsMarshal.dll</HintPath>
		</Reference>
	</ItemGroup>

	<Target Name="CopyDataFiles" AfterTargets="PostBuildEvent">
		<ItemGroup>
			<Files Include="$(OutDir)ChartTools*.dll;$(OutDir)ChartTools*.xml"/>
		</ItemGroup>
		<Copy
			SourceFiles="@(Files)"
			DestinationFolder="$(ProjectDir)artifacts"
			SkipUnchangedFiles="true" />
	</Target>

</Project>
