<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <SignAssembly>False</SignAssembly>
    <Description>Library for editing Clone Hero song files in .NET</Description>
    <PackageProjectUrl></PackageProjectUrl>
    <PackageReadmeFile>$(SolutionDir)/../README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/TheBoxyBear/charttools</RepositoryUrl>
    <NeutralLanguage>en-CA</NeutralLanguage>
    <PackageLicenseFile>$(SolutionDir)/../LICENSE</PackageLicenseFile>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <Company>TheBoxyBear</Company>
  </PropertyGroup>

  <PropertyGroup>
    <PackageLicenseFile>$(SolutionDir)/../LICENSE</PackageLicenseFile>
    <PackageReadmeFile>$(SolutionDir)/../README.md</PackageReadmeFile>
  </PropertyGroup>


</Project>
