<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RefTargetFramework>net10.0</RefTargetFramework>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <SignAssembly>False</SignAssembly>
    <Description>Library for editing Clone Hero song files in .NET</Description>
    <PackageProjectUrl></PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <RunPostBuildEvent>OnOutputUpdated</RunPostBuildEvent>
    <PolyPublic>true</PolyPublic>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Ref'">
    <TargetFramework>$(RefTargetFramework)</TargetFramework>
    <ProduceOnlyReferenceAssembly>true</ProduceOnlyReferenceAssembly>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' != 'Ref'">
    <TargetFrameworks>$(MultiTargetFrameworks)</TargetFrameworks>
    <ProduceOnlyReferenceAssembly>false</ProduceOnlyReferenceAssembly>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <InternalsVisibleTo Include="$(TestAssemblies)"/>
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0' Or '$(TargetFramework)' == 'netstandard2.1'">
    <Reference Include="Bcl.CollectionsMarshal">
      <HintPath>..\Dependencies\bin\$(TargetFramework)\Bcl.CollectionsMarshal.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ChartTools.Common\ChartTools.Common.csproj" Properties="TargetFramework=$(TargetFramework)" />
    <Using Include="ChartTools.Extensions.MemoryExtensions" Static="true"/>
  </ItemGroup>

  <ItemGroup Condition="'$(ProduceOnlyReferenceAssembly)' != 'true'">
    <ProjectReference Include="..\ChartTools.Generator\ChartTools.Generator.csproj" OutputItemType="Analyzer"/>
  </ItemGroup>

  <Target Name="CopyDataFiles" AfterTargets="PostBuildEvent" Condition="'$(TargetFramework)' == '$(RefTargetFramework)'">
    <ItemGroup>
      <Files Include="$(OutDir)ChartTools*.dll;$(OutDir)ChartTools*.xml" />
    </ItemGroup>
    <Copy SourceFiles="@(Files)" DestinationFolder="$(ProjectDir)artifacts" SkipUnchangedFiles="true" />
  </Target>

</Project>
