using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics;
using System.Text;

using System.Linq;

namespace ChartTools.Generator;

[Generator]
public class MetadataMapGenerator : IIncrementalGenerator
{
	private const string
		MetadataType       = "Metadata",
		MapperNamespace    = $"{nameof(ChartTools)}.{nameof(Meta)}.Mapping",
		AttributeNamespace = $"{nameof(ChartTools)}.{nameof(Meta)}";

	private record class MetadataProperty
		(string Name, string Type, string ContainingType, MetadataKeyAttribute Attribute);

	private record class MetadataGroupProperty(string Name, string Type, string ContainingType);

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		if (!Debugger.IsAttached)
		{
			// Uncomment this line to be prompted to debug on generation
			//Debugger.Launch();
		}

		IncrementalValueProvider<ImmutableArray<MetadataGroupProperty>> groups =
			context.SyntaxProvider.ForAttributeWithMetadataName(
				$"{AttributeNamespace}.{nameof(MetadataGroupAttribute)}",
				predicate: static (node, _) => node is PropertyDeclarationSyntax,
				transform: static (context, _) => new MetadataGroupProperty(
				Name: context.TargetSymbol.Name,
				Type: (context.TargetSymbol as IPropertySymbol)!.Type.Name,
				ContainingType: context.TargetSymbol.ContainingType.Name))
			.Collect();

		IncrementalValuesProvider<MetadataProperty> provider =
			context.SyntaxProvider.ForAttributeWithMetadataName($"{AttributeNamespace}.{nameof(MetadataKeyAttribute)}",
				predicate: static (node, _) => node is PropertyDeclarationSyntax,
				transform: static (context, _) =>
				{
					IPropertySymbol target = (IPropertySymbol)context.TargetSymbol;
					AttributeData attribute = context.Attributes[0];

					KeyValuePair<string, TypedConstant> mappable =
						attribute.NamedArguments
							.FirstOrDefault(static arg => arg.Key == nameof(MetadataKeyAttribute.Mappable));

					FileType attFileType = (FileType)attribute.ConstructorArguments[0].Value!;
					string attKey = (string)attribute.ConstructorArguments[1].Value!;

					return new MetadataProperty(
						Name: target.Name,
						Type: target.Type.TypeKind == TypeKind.Class
						? target.Type.Name
						// Extract the underlying type from Nullable<T>
						: (target.Type as INamedTypeSymbol)!.TypeArguments[0].Name,
						Attribute: mappable.Key is null
							? new(attFileType, attKey)
							: new(attFileType, attKey) { Mappable = (bool)mappable.Value.Value! },
						ContainingType: target.ContainingType.Name);
				});

		RegisterMapper("MetadataChartMapper", FileType.Chart);
		RegisterMapper("MetadataIniMapper", FileType.Ini);

		void RegisterMapper(string mapperType, FileType fileType)
		{
			IncrementalValuesProvider<MetadataProperty> fileTypeProvider = provider
				.Where(prop => prop.Attribute.FileType == fileType);

			context.RegisterImplementationSourceOutput(
			   fileTypeProvider
				   .Where(static prop => prop.Attribute.Mappable).Collect()
			   .Combine(groups),
			   (ctx, tuple) => GenerateMapMethods(mapperType, in ctx, tuple));

			context.RegisterImplementationSourceOutput(fileTypeProvider.Collect().Combine(groups),
				(ctx, tuple) => GenerateNonMapMethods(mapperType, in ctx, tuple));
		}
	}

	private static Dictionary<string, string> GetGroupPaths(in ImmutableArray<MetadataGroupProperty> groups)
	{
		Dictionary<string, string> paths = new(groups.Length);

		do
			foreach (MetadataGroupProperty group in groups)
			{
				if (paths.ContainsKey(group.Type))
					continue;

				if (group.ContainingType is MetadataType)
					paths[group.Type] = $".{group.Name}";
				else if (paths.TryGetValue(group.ContainingType, out var path))
					paths[group.Type] = $"{path}.{group.Name}";
			}
		while (paths.Count < groups.Length);

		// Shorthand to not have to check for root
		paths[MetadataType] = string.Empty;

		return paths;
	}

	private static void GenerateMapMethods
		(string className, in SourceProductionContext context,
		(ImmutableArray<MetadataProperty>, ImmutableArray<MetadataGroupProperty>) tuple)
	{
		var (props, groups) = tuple;

		Dictionary<string, string> paths = GetGroupPaths(in groups);

		StringBuilder builder = new(
$$"""
// <auto-generated/>

using ChartTools.IO;

namespace {{MapperNamespace}};

internal sealed partial class {{className}}
{

""");

		if (context.CancellationToken.IsCancellationRequested)
			return;

		BuildTryGet(builder, in props, paths);

		if (context.CancellationToken.IsCancellationRequested)
			return;

		BuildTrySet(builder, in props, paths);

		builder.AppendLine(
"""
}
""");

		if (context.CancellationToken.IsCancellationRequested)
			return;

		context.AddSource($"{className}_Map.g.cs", builder.ToString());
	}

	private static void GenerateNonMapMethods
	(string className, in SourceProductionContext context,
	(ImmutableArray<MetadataProperty>, ImmutableArray<MetadataGroupProperty>) tuple)
	{
		var (props, groups) = tuple;

		Dictionary<string, string> paths = GetGroupPaths(in groups);

		StringBuilder builder = new(
$$"""
// <auto-generated/>

using ChartTools.IO;

namespace {{MapperNamespace}};

internal sealed partial class {{className}}
{

""");

		if (context.CancellationToken.IsCancellationRequested)
			return;

		BuildTryRemove(builder, in props, paths);

		if (context.CancellationToken.IsCancellationRequested)
			return;

		BuildGetAll(builder, in props, paths);

		builder.AppendLine(
"""
}
""");

		if (context.CancellationToken.IsCancellationRequested)
			return;

		context.AddSource($"{className}_Misc.g.cs", builder.ToString());
	}

	private static void BuildTryGet(StringBuilder builder, in ImmutableArray<MetadataProperty> props, Dictionary<string, string> paths)
	{
		builder.AppendLine(
$$"""
	private static partial bool TryGetFromAttribute({{MetadataType}} metadata, in ReadOnlySpan<char> key, out string value)
		=> (value = key switch
		{
""");

		foreach (MetadataProperty prop in props)
		{
			string toStringSuffix = prop.Type is "String"
				? string.Empty : "?.ToString()";

			builder.AppendLine(
$"""
			"{prop.Attribute.Key}" => metadata{paths![prop.ContainingType]}.{prop.Name}{toStringSuffix},
""");
		}

		builder.AppendLine(
"""
			_ => null
		}) is not null;
""");
	}

	private static void BuildTrySet(StringBuilder builder, in ImmutableArray<MetadataProperty> props, Dictionary<string, string> paths)
	{
		builder.AppendLine(
$$"""
	private static partial bool TrySetFromAttribute({{MetadataType}} metadata, in ReadOnlySpan<char> key, in ReadOnlySpan<char> value)
	{
		switch (key)
		{
""");

		foreach (MetadataProperty prop in props)
		{
			string setCode = prop.Type == "String"
				? "value.ToString()"
				: $"ValueParser.Parse<{prop.Type}>(in value, \"{prop.Name}\")";

			builder.AppendLine(
$"""
			case "{prop.Attribute.Key}":
				metadata{paths![prop.ContainingType]}.{prop.Name} = {setCode};
				return true;
""");
		}

		builder.AppendLine(
"""
			default:
				return false;
		}
	}
""");
	}

	private static void BuildTryRemove(StringBuilder builder, in ImmutableArray<MetadataProperty> props, Dictionary<string, string> paths)
	{
		builder.AppendLine(
$$"""
	private static partial bool TryRemoveFromAttribute({{MetadataType}} metadata, in ReadOnlySpan<char> key)
	{
		switch (key)
		{
""");

		foreach (MetadataProperty prop in props)
		{
			builder.AppendLine(
$"""
			case "{prop.Attribute.Key}":
				metadata{paths![prop.ContainingType]}.{prop.Name} = null;
				return true;
""");
		}

		builder.AppendLine(
"""
			default:
				return false;
		}
	}
""");
	}

	private static void BuildGetAll(StringBuilder builder, in ImmutableArray<MetadataProperty> props, Dictionary<string, string> paths)
	{
		builder.AppendLine(
$$"""
	private partial IEnumerable<TextEntry> GetAllFromAttributes({{MetadataType}} metadata)
	{
		string value;
""");

		if (props.Length == 0)
		{
			builder.AppendLine(
"""
		return Eumerable.Empty<TextEntry>();
""");

			return;
		}

		foreach (MetadataProperty prop in props)
		{
			builder.AppendLine(
$"""
		if ((value = Get(metadata, "{prop.Attribute.Key}")) is not null)
			yield return new("{prop.Attribute.Key}", value);
""");
		}

		builder.AppendLine(
"""
	}
""");
	}
}
