using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics;

using ChartTools.Attributes.Metadata;
using System.Text;

namespace ChartTools.Generator;

[Generator]
internal class MetadataMapGenerator : IIncrementalGenerator
{
	public const string AttributeNamespace = $"{nameof(ChartTools)}.{nameof(Attributes)}.{nameof(Attributes.Metadata)}";

	private record class MetadataProperty(string Name, string Type, string Key, string ContainingType);

	private record class MetadataGroupProperty(string Name, string Type, string ContainingType);

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		if (!Debugger.IsAttached)
		{
			// Uncomment this line to be prompted to debug on generation
			//Debugger.Launch();
		}

		var chartProvider = CreatePropertyProvider(nameof(MetadataChartKeyAttribute), in context);
		var iniProvider   = CreatePropertyProvider(nameof(MetadataIniKeyAttribute), in context);

		var groupProvider = context.SyntaxProvider.ForAttributeWithMetadataName(
			$"{AttributeNamespace}.{nameof(MetadataGroupAttribute)}",
			predicate: static (node, _) => node is PropertyDeclarationSyntax,
			transform: static (context, _) => new MetadataGroupProperty(
			Name: context.TargetSymbol.Name,
			Type: (context.TargetSymbol as IPropertySymbol)!.Type.Name,
			ContainingType: context.TargetSymbol.ContainingType.Name));

		context.RegisterImplementationSourceOutput(chartProvider.Collect().Combine(groupProvider.Collect()),
			static (ctx, tuple) => GenerateMapMethods("MetadataChartMapper", in ctx, tuple));

		context.RegisterImplementationSourceOutput(iniProvider.Collect().Combine(groupProvider.Collect()),
			static (ctx, tuple) => GenerateMapMethods("MetadataIniMapper", in ctx, tuple));
	}

	private static IncrementalValuesProvider<MetadataProperty> CreatePropertyProvider
		(string attributeClass, in IncrementalGeneratorInitializationContext context)
		=> context.SyntaxProvider.ForAttributeWithMetadataName($"{AttributeNamespace}.{attributeClass}",
			predicate: static (node, _) => node is PropertyDeclarationSyntax,
			transform: static (context, _) =>
			{
				IPropertySymbol target = (IPropertySymbol)context.TargetSymbol;

				return new MetadataProperty(
					Name: target.Name,
					Type: target.Type.TypeKind == TypeKind.Class
					? target.Type.Name
					// Extract the underlying type from Nullable<T>
					: (target.Type as INamedTypeSymbol)!.TypeArguments[0].Name,
					Key: context.Attributes[0].ConstructorArguments[0].Value!.ToString(),
					ContainingType: target.ContainingType.Name);
			});

	private static void GenerateMapMethods
		(string className, in SourceProductionContext context,
		(ImmutableArray<MetadataProperty>, ImmutableArray<MetadataGroupProperty>) tuple)
	{
		var (properties, groups) = tuple;

		Dictionary<string, string> groupPaths = new(groups.Length);

		// Consider finding a way to only process this once and pass to chart and ini
		do
			foreach (var group in groups)
			{
				if (groupPaths.ContainsKey(group.Type))
					continue;

				if (group.ContainingType == "Metadata")
					groupPaths[group.Type] = $".{group.Name}";
				else if (groupPaths.TryGetValue(group.ContainingType, out var path))
					groupPaths[group.Type] = $"{path}.{group.Name}";
			}
		while (groupPaths.Count < groups.Length);

		// Shorthand to not have to check for root
		groupPaths["Metadata"] = string.Empty;

		StringBuilder codeBuilder = new(
$$"""

// <auto-generated/>

namespace ChartTools.Meta.Mapping;

internal sealed partial class {{className}}
{

""");

		if (context.CancellationToken.IsCancellationRequested)
			return;

		BuildTryGet();

		if (context.CancellationToken.IsCancellationRequested)
			return;

		BuildTrySet();

		if (context.CancellationToken.IsCancellationRequested)
			return;

		BuildTryRemove();

		codeBuilder.AppendLine(
$$"""
}
""");

		context.AddSource($"{className}.g.cs", codeBuilder.ToString());

		void BuildTryGet()
		{
			codeBuilder.AppendLine(
$$"""
	private static partial bool TryGetFromAttribute(Metadata metadata, in ReadOnlySpan<char> key, out string value)
	{
		switch (key)
		{
""");

			foreach (var prop in properties)
			{
				string toStringSuffix = prop.Type == "String"
					? string.Empty : "?.ToString()";

				codeBuilder.AppendLine(
$"""
			case "{prop.Key}":
				value = metadata{groupPaths[prop.ContainingType]}.{prop.Name}{toStringSuffix};
				return true;
""");
			}

			codeBuilder.AppendLine(
$$"""
			default:
				value = null;
				return false;
		}
	}
""");
		}

		void BuildTrySet()
		{
			codeBuilder.AppendLine(
$$"""
	private static partial bool TrySetFromAttribute(Metadata metadata, in ReadOnlySpan<char> key, in ReadOnlySpan<char> value)
	{
		switch (key)
		{
""");

			foreach (var prop in properties)
			{
				string setCode = prop.Type == "String"
					? "value.ToString()"
					: $"ChartTools.IO.ValueParser.Parse<{prop.Type}>(in value, \"{prop.Name}\")";

				codeBuilder.AppendLine(
$"""
			case "{prop.Key}":
				metadata{groupPaths[prop.ContainingType]}.{prop.Name} = {setCode};
				return true;
""");
			}

			codeBuilder.AppendLine(
$$"""
			default:
				return false;
		}
	}
""");
		}

		void BuildTryRemove()
		{
			codeBuilder.AppendLine(
$$"""
	private static partial bool TryRemoveFromAttribute(Metadata metadata, in ReadOnlySpan<char> key)
	{
		switch (key)
		{
""");

			foreach (var prop in properties)
			{
				codeBuilder.AppendLine(
$"""
			case "{prop.Key}":
				metadata{groupPaths[prop.ContainingType]}.{prop.Name} = null;
				return true;
""");
			}

			codeBuilder.AppendLine(
$$"""
			default:
				return false;
		}
	}
""");
		}
	}
}
